import type { Metadata } from 'next'
import { IBM_Plex_Sans_Thai_Looped } from 'next/font/google'

import Nav from '@/app/components/Nav'

import './globals.scss'

const IBM_Plex_Sans = IBM_Plex_Sans_Thai_Looped({ subsets : ['latin'],  weight: ['300','600'] })

export const metadata: Metadata = {
  title: 'Luna Exchange',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={IBM_Plex_Sans.className}>
        <Nav />
        <main className="content">
        {children}
        </main>
        </body>
    </html>
  )
}
